# Generated by Django 4.2.6 on 2023-12-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('tipo_user', models.IntegerField(choices=[(0, 'Persona sin Auto'), (1, 'Conductor')])),
                ('viaje_ida', models.IntegerField(choices=[(0, 'Sin Viaje Ida'), (1, 'Viaje Ida Tomado')])),
                ('viaje_vuelta', models.IntegerField(choices=[(0, 'Sin Viaje Ida'), (1, 'Viaje Ida Tomado')])),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('duenno', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('salida', models.CharField(max_length=15)),
                ('fecha', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('tipo_viaje', models.IntegerField(choices=[(0, 'Ida'), (1, 'Vuelta')])),
                ('estado_viaje', models.IntegerField(choices=[(0, 'Viaje Oculto'), (1, 'Viaje Visible')])),
            ],
        ),
        migrations.CreateModel(
            name='ViajeTomado',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[(0, 'Viaje Finalizado'), (1, 'Viaje en Curso')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaApp.usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebaApp.viaje')),
            ],
        ),
    ]
